#!/usr/bin/ash

run_latehook() {
    local composefs

    composefs="$(getarg composefs)"
    if [ -z "$composefs" ]; then
        return 0
    fi

    /usr/bin/composefs-setup-root --sysroot /new_root
}
